<!DOCTYPE html>
<html>
<head>
 <link href="/normalize.css" rel="stylesheet">
 <title>Flight</title>
 </head>
 <body>
 <img src="xd7VP.jpg">
 <p>There are 4 forces acting upon an an object in flight
 <br>Motions that keep the object going foward</br>
 
 <ol type=I>
 <li>Thrust</li>
 <li>Lift</li>
 </ol>
 <br>Motions that keep the object from moving foward</br>
 <ol type=I>
 <li>Drag</li>
 <li>Weight</li>
 </ol>
 
 </body>
</html>
